name: we_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For using cupertino icons
  cupertino_icons: ^1.0.2

  # For integrating firebase
  firebase_core: ^2.9.0

  # For handling google sign in
  firebase_auth: ^4.6.1

  # For accessing cloud firestore database
  cloud_firestore: ^4.5.1

  # For accessing firebase storage
  firebase_storage: ^11.1.0

  # For handling firebase authentication
  google_sign_in: ^6.1.0

  # For handling firebase authentication for web
  google_sign_in_web: ^0.12.0+1

  # For showing network images
  cached_network_image: ^3.2.3

  # For picking images
  image_picker: ^0.8.7+3

  # For showing emojis
  emoji_picker_flutter: ^1.5.4

  # For accessing firebase messaging (push notifications) for mobile
  firebase_messaging: ^14.4.1

  # For calling RestAPIs
  http: ^0.13.6

  # For creating notification channel for mobile
  flutter_notification_channel: ^2.0.0

  # For showing Toasts on monile
  fluttertoast: ^8.2.1

  # For saving images to gallery on mobile
  gallery_saver: ^2.3.2

  # For saving on web apps
  image_downloader_web: ^2.0.2

  # For displaying different for android, web
  responsive_builder: ^0.7.0

  # For date time formatting
  intl: ^0.18.1

  # For uploading images from computer
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#   flutter_launcher_icons: "^0.13.0"

# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "images/icon.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true
#   web:
#     generate: true
#     image_path: "images/icon.png"
#   windows:
#     generate: true
#     image_path: "images/icon.png"
#     icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
